name: Pull Request Actions
on:
  push:
  pull_request:
    branches: [master]

jobs:
  install_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install packages
        id: install
        run: npm ci
      - name: Lint
        id: lint
        run: npm run lint
      - name: Test
        id: test
        run: npm run test
        continue-on-error: true
      - name: send log if tests fail
        if: steps.test.outcome == 'failure'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Tests failed
      - name: exit if tests fail
        run: exit 1
      - name: Build
        id: build
        run: npm run build

      