name: Pull Request Actions
on:
  push:
  pull_request:
    branches: [master]

jobs:
  install_and_build:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
    - run: npm ci
    - name: Lint
    - run: npm run lint
    - name: Test
    - run: npm run test
      